using OpenPOS_Settings;
using RestSharp;

namespace OpenPOS_TikkiePayment
{
    public class TikkiePaymentService
    {
        /// <summary>
        /// Requesting to create a new payment request with Tikkie
        /// </summary>
        /// <param name="amountInCents">The due amount in cents</param>
        /// <param name="transactionId">A custom transaction ID for administrative purposes</param>
        /// <param name="desc">A description of the payment</param>
        /// <returns>A JSON string containing all the payment information</returns>
        public string CreatePaymentRequest(int amountInCents, int transactionId, string desc)
        {
            var client = new RestClient(ApplicationSettings.TikkieSet.BaseUrl);
            var request = new RestRequest("/paymentrequests", Method.Post);
            request.AddHeader("X-App-Token", ApplicationSettings.TikkieSet.AppToken);
            request.AddHeader("Content-Type", "application/json");
            request.AddHeader("Accept", "application/json");
            request.AddHeader("API-Key", ApplicationSettings.TikkieSet.Key);
            request.AddJsonBody(new
            {
               description = desc,
               amountInCents = amountInCents,
               expiryDate = DateTime.Today.AddDays(1).ToString("yyyy-MM-dd"),
               referenceId = transactionId.ToString(),
            });

            RestResponse response = client.Execute(request);
            if (response.Content != null)
            {
                return response.Content;
            }

            return null;
        }
        
        /// <summary>
        /// This function returns all information for a specific transaction.
        /// </summary>
        /// <param name="paymentRequestToken">The payment request token generated by the Tikkie API</param>
        /// <returns>a JSON string containing all the payment information.</returns>
        public string GetTransactionInformation(string paymentRequestToken)
        {
            var client = new RestClient(ApplicationSettings.TikkieSet.BaseUrl);
            var request = new RestRequest($"/paymentrequests/{paymentRequestToken}");
            request.AddHeader("X-App-Token", ApplicationSettings.TikkieSet.AppToken);
            request.AddHeader("Accept", "application/json");
            request.AddHeader("API-Key", ApplicationSettings.TikkieSet.Key);
            
            RestResponse response = client.Execute(request);
            if (response.Content != null)
            {
                return response.Content;
                
            }

            return null;
        }
    }
}