# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Continuous integration

on:
  push:
    branches: 
      - "master"
      - "development/**"
#       - "bug-fix/**"
  pull_request:
    branches: 
      - "master"
      - "development/**"
#       - "feature/**"
#       - "bug-fix/**"
  
  workflow_dispatch:

env:
    DOTNETVERSION: 7.0.x

jobs:
  WindowsWorkflow:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNETVERSION }}

    - name: Add Appsettings
      uses: microsoft/variable-substitution@v1
      with:
          files: 'OpenPOS/**.json'
      env:
          TIKKIE_API.Key: ${{ secrets.TIKKIE_API_KEY }}
          DATABASE_CONNECTION.connection_string: ${{ secrets.DB_CONN_STRING }}
    
    - name: Install .NET MAUI
      shell: bash
      run: |
          dotnet nuget locals all --clear 
          dotnet workload install maui
          dotnet workload install android ios maccatalyst tvos macos maui wasm-tools
    
    - name: Restore nuget packages
      run: dotnet restore OpenPOS.sln

    - name: Build with .NET
      run: dotnet build --configuration Release
    
    - name: Test with .NET
      run: dotnet test --configuration Release --no-build --verbosity normal
      
#   AndroidWorkflow:
#     runs-on: windows-latest
#     steps:
#     - uses: actions/checkout@v2
#     - name: Setup .NET
#       uses: actions/setup-dotnet@v1
#       with:
#         dotnet-version: ${{ env.DOTNETVERSION }}
#
#     - name: Install .NET MAUI
#       shell: bash
#       run: |
#           dotnet nuget locals all --clear
#           dotnet workload install maui
#           dotnet workload install android ios maccatalyst tvos macos maui wasm-tools
#
#     - name: Restore nuget packages
#       run: dotnet restore OpenPOS.sln
#
#     - name : Build Android App
#       shell: bash
#       run: dotnet publish -f:net7.0-android -c:Release
#
#     - name: Test with .NET
#       run: dotnet test --configuration Release --no-build --verbosity normal
#
#   MacOSWorkflow:
#     runs-on: macos-latest
#     steps:
#     - uses: actions/checkout@v2
#     - name: Setup .NET
#       uses: actions/setup-dotnet@v1
#       with:
#         dotnet-version: ${{ env.DOTNETVERSION }}
#
#     - name: Install .NET MAUI
#       shell: bash
#       run: |
#           dotnet nuget locals all --clear
#           dotnet workload install maui
#           dotnet workload install maccatalyst macos maui wasm-tools
#
#     - name: Restore nuget packages
#       run: dotnet restore OpenPOS.sln
#
#     - name: Build with .NET
#       run: |
#           dotnet publish -f net7.0-maccatalyst
#
#     - name: Test with .NET
#       run: dotnet test --configuration Release --no-build --verbosity normal
      
  # iOSWorkflow:
  #   runs-on: macos-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Setup .NET
  #     uses: actions/setup-dotnet@v1
  #     with:
  #       dotnet-version: ${{ env.DOTNETVERSION }}
    
  #   - name: Install .NET MAUI
  #     shell: bash
  #     run: |
  #         dotnet nuget locals all --clear 
  #         dotnet workload install maui
  #         dotnet workload install android ios maccatalyst tvos macos maui wasm-tools
    
  #   - name: Restore nuget packages
  #     run: dotnet restore OpenPOS.sln

  #   - name: Build with .NET
  #     run: dotnet publish -f net7.0-ios
    
  #   - name: Test with .NET
  #     run: dotnet test --configuration Release --no-build --verbosity normal
