# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET Testing

on:
  push:
    branches: 
      - "master"
      - "develop"
  pull_request:
    branches: 
      - "master"
      - "develop"
      - "feature**"
      - "bug**"
  
  workflow_dispatch:

env:
    DOTNETVERSION: 7.0.x

jobs:
  # workflow that builds and test .NET MAUI
  WindowsWorkflow:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNETVERSION }}
    
    - name: Install .NET MAUI
      shell: bash
      run: |
          dotnet nuget locals all --clear 
          dotnet workload install maui
          dotnet workload install android ios maccatalyst tvos macos maui wasm-tools

    - name: Build with .NET
      run: dotnet build --configuration Release
    
    - name: Test with .NET
      run: dotnet test --configuration Release --no-build --verbosity normal
  
      
