# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
# change dddd

name: Continuous integration

on:
  push:
    branches: 
      - "master"
#       - "development/**"
#      - "bug-fix/**"
  pull_request:
    branches: 
      - "master"
      - "development/**"
#       - "feature/**"
#       - "bug-fix/**"
  
  workflow_dispatch:

env:
    DOTNETVERSION: 7.0.x

jobs:
  WindowsWorkflow:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNETVERSION }}

    - name: Create appsettings.json
      id: appsettings
      uses: jsdaniell/create-json@v1.2.1
      with:
          name: "appsettings.json"
          json: ${{ secrets.APPSETTINGS }}
          dir: 'OpenPOS-APP\'

    - name: Create appsettings.test.json
      id: testappsettings
      uses: jsdaniell/create-json@v1.2.1
      with:
          name: "appsettings.test.json"
          json: ${{ secrets.APPSETTINGS }}
          dir: 'OpenPOS-Testing\'

    - name: Install .NET MAUI
      shell: bash
      run: |
          dotnet nuget locals all --clear 
          dotnet workload install maui
          dotnet workload install android ios maccatalyst tvos macos maui wasm-tools
    
    - name: Restore nuget packages
      run: dotnet restore OpenPOS.sln

    - name: Build with .NET
      run: dotnet build --configuration Release
    
    - name: Test with .NET
      run: dotnet test --configuration Release --no-build --verbosity normal
      
#   AndroidWorkflow:
#     runs-on: windows-latest
#     steps:
#     - uses: actions/checkout@v2
#     - name: Setup .NET
#       uses: actions/setup-dotnet@v1
#       with:
#         dotnet-version: ${{ env.DOTNETVERSION }}
#
#     - name: Install .NET MAUI
#       shell: bash
#       run: |
#           dotnet nuget locals all --clear
#           dotnet workload install maui
#           dotnet workload install android ios maccatalyst tvos macos maui wasm-tools
#
#     - name: Restore nuget packages
#       run: dotnet restore OpenPOS.sln
#
#     - name : Build Android App
#       shell: bash
#       run: dotnet publish -f:net7.0-android -c:Release
#
#     - name: Test with .NET
#       run: dotnet test --configuration Release --no-build --verbosity normal
#
  MacOSWorkflow:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNETVERSION }}

    - name: Install .NET MAUI
      shell: bash
      run: |
          dotnet nuget locals all --clear
          dotnet workload install maui
          dotnet workload install maccatalyst macos maui wasm-tools

    - name: Create appsettings.json
      id: appsettings
      uses: jsdaniell/create-json@v1.2.1
      with:
          name: "appsettings.json"
          json: ${{ secrets.APPSETTINGS }}
          dir: 'OpenPOS-APP/'

    - name: Create appsettings.test.json
      id: testappsettings
      uses: jsdaniell/create-json@v1.2.1
      with:
          name: "appsettings.test.json"
          json: ${{ secrets.APPSETTINGS }}
          dir: 'OpenPOS-Testing/'

    - name: Restore nuget packages
      run: dotnet restore OpenPOS.sln

    - name: Build with .NET
      run: dotnet build --configuration Release --no-restore -p:TargetFramework=net7.0

    - name: Test with .NET
      run: dotnet test --configuration Release --no-build --verbosity normal
      
  # iOSWorkflow:
  #   runs-on: macos-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Setup .NET
  #     uses: actions/setup-dotnet@v1
  #     with:
  #       dotnet-version: ${{ env.DOTNETVERSION }}
    
  #   - name: Install .NET MAUI
  #     shell: bash
  #     run: |
  #         dotnet nuget locals all --clear 
  #         dotnet workload install maui
  #         dotnet workload install android ios maccatalyst tvos macos maui wasm-tools
    
  #   - name: Restore nuget packages
  #     run: dotnet restore OpenPOS.sln

  #   - name: Build with .NET
  #     run: dotnet publish -f net7.0-ios
    
  #   - name: Test with .NET
  #     run: dotnet test --configuration Release --no-build --verbosity normal
