name: Add issue to project

on:
  issues:
    types:
      - opened
      - edited

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.3.0
        with:
          project-url: https://github.com/orgs/ICTOOSDDd4/projects/2
          column-name: "Product Backlog"
          github-token: ${{ secrets.GITBOT }}
          labeled: feature, documentation, enhancement
          label-operator: OR
