name: Add issue to project

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
    # - name: Add issue to project
    #   uses: actions/add-to-project@v0.3.0
    #   with:
    #     project-url: https://github.com/orgs/ICTOOSDDd4/projects/2
    #     column-name: "Product Backlog"
    #     github-token: ${{ secrets.GITBOT }}
    #     labeled: feature, documentation, enhancement
    #     label-operator: OR
    - name: Add issue to project
      if: ${{ contains(github.event.issue.labels.*.name, 'feature') || contains(github.event.issue.labels.*.name, 'documentation') || contains(github.event.issue.labels.*.name, 'enhancement') }}
      uses: docker://takanabe/github-actions-automate-projects:v0.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITBOT }}
        GITHUB_PROJECT_URL: https://github.com/orgs/ICTOOSDDd4/projects/2
        GITHUB_PROJECT_COLUMN_NAME: Product Backlog
      
    - name: Sending discord message
      if: ${{ contains(github.event.issue.labels.*.name, 'feature') || contains(github.event.issue.labels.*.name, 'documentation') || contains(github.event.issue.labels.*.name, 'enhancement') }}
      uses: stegzilla/discord-notify@v4
      with:
        webhook_url: ${{ secrets.DISCORD_WEBHOOK_ACTIONS_STATUS }}
        title: "New issue added to project"
        message: "**${{ github.event.issue.title }}** has been added to the project\n${{ github.event.pull_request.html_url }}"
        include_image: true
        avatar_url: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png        
        username: GitHub Project Mananger

    - name: Adding bug to project
      if: ${{ contains(github.event.issue.labels.*.name, 'bug')}}
      uses: docker://takanabe/github-actions-automate-projects:v0.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITBOT }}
        GITHUB_PROJECT_URL: https://github.com/orgs/ICTOOSDDd4/projects/2
        GITHUB_PROJECT_COLUMN_NAME: Product Backlog
    
    - name: Sending discord message
      if: ${{ contains(github.event.issue.labels.*.name, 'bug')}}
      uses: stegzilla/discord-notify@v4
      with:
        webhook_url: ${{ secrets.DISCORD_WEBHOOK_ACTIONS_STATUS }}
        title: "New bug added to project"
        message: "**${{ github.event.issue.title }}** has been added to the bug project\n${{ github.event.pull_request.html_url }}"
        include_image: true
        avatar_url: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
        username: GitHub Project Mananger
    

      