name: Checking issue compliance workflow

on:
  issues:
    types:
      - opened

jobs:
  close_issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/github-script@v3
      - name: Close issue if it doesn't have a label
        if: join(github.event.issue.labels) == ''
        with:
          github-token: ${{secrets.GITBOT}}
          
          
