name: Checking issue compliance workflow

on:
  issues:
    types:
      - opened

jobs:
  close_issue:
    runs-on: ubuntu-latest
    steps:
      - if: join(github.event.issue.labels) == ''
        uses: peter-evans/close-issue@v2.2.0
        name: Close issue if it doesn't have a label
        with:
          comment: Issue doesn't have a label. Closing it.
          
          
